Email_Address="//input[@type='email']"
Phone="//input[@type='tel']"
address="//textarea[@rows='3']"

Male_Radio_Button= "(//input[@name='radiooptions'])[1]"
Female_Radio_Button="(//input[@name='radiooptions'])[2]"
Cricket_Check_Box = "checkbox1"
Movies_CB = "checkbox2"
Hockey_CB = "checkbox3"
Lang_DropDown = "msdd"
Thai_DropDownSelection = "//a[text()='Thai']"
Thai_CloseButton = "//div[text()='Thai']/span"
Thai_CloseButton ="//span[@class='ui-icon ui-icon-close']"
Swedish_DD_Selection = "//a[text()='Swedish']"
Skills_DD = "//select[@id='Skills']"
Country_dropdown ="//select[@id='countries']"
select_country="//span[@class='select2-selection select2-selection--single']"
country_search="//input[@class='select2-search__field']"
year_dd="yearbox"
month_dd="//select[@placeholder='Month']"
day_dd="daybox"
pwd="firstpassword"
cnf_pwd="secondpassword"
submit="//button[@id='submitbtn']"

JqueryUI_Frame = "//iframe"
Drag_Draggable = "draggable"
Drag_Dropable = "droppable"
MouseHover_Image = "//img[@title='Support the JS Foundation']"
search="//input"

MOuseHover_Tutorials_Link = "//header/descendant::span[text()='Tutorial']"
About="(//span[text()='ABOUT'])[1]"
facebook="(//a[@title='Facebook'])[1]"
